package com.pdfmaster.gateway.config;

import java.util.List;
import org.springframework.cloud.gateway.filter.ratelimit.KeyResolver;
import org.springframework.cloud.gateway.filter.ratelimit.RateLimiter;
import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Declarative route table for the gateway.
 *
 * <p>Each route strips the {@code /api/v1/<service>} prefix and forwards to the corresponding
 * downstream service. Every route is rate-limited via Redis and propagates an {@code
 * X-Correlation-Id} request header generated by {@link
 * com.pdfmaster.gateway.adapter.in.CorrelationIdWebFilter} when the inbound request does not carry
 * one.
 */
@Configuration
public class RouteConfig {

  private static final int STRIP_PREFIX_API_V1 = 2;

  private record DownstreamRoute(String id, String pathPattern, String defaultUri) {}

  private static final List<DownstreamRoute> DOWNSTREAMS =
      List.of(
          new DownstreamRoute("auth", "/api/v1/auth/**", "http://localhost:8081"),
          new DownstreamRoute("pdf", "/api/v1/pdf/**", "http://localhost:8082"),
          new DownstreamRoute("ai", "/api/v1/ai/**", "http://localhost:8083"),
          new DownstreamRoute("esign", "/api/v1/esign/**", "http://localhost:8084"),
          new DownstreamRoute("billing", "/api/v1/billing/**", "http://localhost:8085"),
          new DownstreamRoute("notifications", "/api/v1/notifications/**", "http://localhost:8086"),
          new DownstreamRoute("convert", "/api/v1/convert/**", "http://localhost:8087"),
          new DownstreamRoute("ocr", "/api/v1/ocr/**", "http://localhost:8088"));

  @Bean
  public RouteLocator gatewayRoutes(
      RouteLocatorBuilder builder,
      GatewayRoutesProperties properties,
      RateLimiter<?> rateLimiter,
      KeyResolver userKeyResolver) {

    RouteLocatorBuilder.Builder routes = builder.routes();
    for (DownstreamRoute downstream : DOWNSTREAMS) {
      String uri = properties.uriFor(downstream.id(), downstream.defaultUri());
      routes.route(
          downstream.id(),
          r ->
              r.path(downstream.pathPattern())
                  .filters(
                      f ->
                          f.stripPrefix(STRIP_PREFIX_API_V1)
                              .requestRateLimiter(
                                  c ->
                                      c.setRateLimiter(rateLimiter)
                                          .setKeyResolver(userKeyResolver)))
                  .uri(uri));
    }
    return routes.build();
  }
}
